// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/products/top": {
            "get": {
                "description": "Returns a fixed list of top 20 products globally",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get top products globally",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.ProductStats"
                            }
                        }
                    }
                }
            }
        },
        "/api/regions/top": {
            "get": {
                "description": "Returns a list of top 30 sales regions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "regions"
                ],
                "summary": "Get top sales regions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.RegionStats"
                            }
                        }
                    }
                }
            }
        },
        "/api/revenue/country/summary": {
            "get": {
                "description": "Returns a paginated list of countries with revenue \u0026 top products",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "revenue"
                ],
                "summary": "Get country revenue summary",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of top products per country",
                        "name": "products",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.CountrySummary"
                            }
                        }
                    }
                }
            }
        },
        "/api/sales/monthly": {
            "get": {
                "description": "Returns aggregated monthly sales data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sales"
                ],
                "summary": "Get monthly sales data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.MonthlySales"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.CountrySummary": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "country_total_revenue": {
                    "type": "number"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ProductRevenueSummary"
                    }
                }
            }
        },
        "response.MonthlySales": {
            "type": "object",
            "properties": {
                "month": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "response.ProductRevenueSummary": {
            "type": "object",
            "properties": {
                "product_name": {
                    "type": "string"
                },
                "total_revenue": {
                    "type": "number"
                },
                "transaction_count": {
                    "type": "integer"
                }
            }
        },
        "response.ProductStats": {
            "type": "object",
            "properties": {
                "product_name": {
                    "type": "string"
                },
                "stock_quantity": {
                    "type": "integer"
                },
                "total_quantity": {
                    "type": "integer"
                }
            }
        },
        "response.RegionStats": {
            "type": "object",
            "properties": {
                "items_sold": {
                    "type": "integer"
                },
                "region": {
                    "type": "string"
                },
                "total_revenue": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
